title: Pilipala
contents:
  - x: 448
    y: 344
    type: link
    path: "/Applications"
  - x: 192
    y: 344
    type: file
    path: Pilipala.app
# flutter_distributor package --platform macos --targets dmg --skip-clean
